### ISSUE TITLE
Let user choose OE value on init

### ISSUE THREAD

**Issue by lucsansag** [mcauser/micropython-74hc595#5]
I'm using this library for a project in which I have OE pulled high with a resistor, so that the outputs will be floating, and then pull it low from MicroPython after writing to the register. This works if I initialize the OE pin with a value of 1 and then switch it with the Pin's off() method, but if I pass the pin to the library's constructor the register writes out the random values it had at startup to the outputs, because the constructor re-initializes the pin with a value of 0. It would be great if there was a parameter to choose whether to set it to 0 or 1 (or just keep its current state).

**Comment by mcauser** [comment]
Hi @lucsansag
You can always pass in `oe = None` (or don't pass it, as `None` is the default) and manage the pin state yourself.
The constructor only tries it initialise the `srclr` and `oe` pins if they are not None.

The `enable` method is a simple wrapper for toggling the `oe` pin.
Bypassing it means just calling `oe(0), oe(1)` or `oe.on(), oe.off()` instead of `sr.enable()`
